### ISSUE TITLE
Alguém realmente usando esse SDK?

### ISSUE THREAD

**Issue by jfoliveira** [Braspag/BraspagApiPhpSdk#12]
Olá, obrigado por disponibilizar esse pacote!

Dei uma olhada rápida nos fontes (ainda não instalei o pacote) e vi o que me parece ser um erro no `composer.json`:
```javascript
"autoload": {
    "classmap": [
        "scr/" // pasta scr não existe, deveria referenciar pasta src?
    ]
  }
```
Como há esse erro prevenindo o uso do autoload - exigindo que o pacote seja consumido de forma procedural utilizando `include` ou `require` - fiquei me perguntando se este SDK está estável e se posso confiar nele para integração com a API da Braspag.

Sabem me responder se este SDK ainda é suportado oficialmente pela Braspag?

Obrigado!

**Comment by paulohenriquesi** [comment]
Bom dia! Ele é suportado sim! Inclusive estamos subindo uma correção hoje haha.

Pode usar a vontade e caso encontre algum problema, só nos avisar =)

**Comment by jfoliveira** [comment]
Obrigado Paulo!
O Packagist ainda não tá atualizando automaticamente alterações no seu pacote. Ainda está fazendo download da versão anterior antes do merge da PR #13 

Você definiu um hook no Github para atualização automática?

Se não tiver criado um, aqui tem um passo a passo de como fazer:
https://packagist.org/about#how-to-update-packages 

Espero que lhe ajude.

**Comment by jfoliveira** [comment]
Mais uma sugestão: se passar a utilizar namespaces em todas as classes do seu pacote, além de facilitar o consumo via cláusula `use Braspag\...` também poderá se livrar do arquivo `BraspagApiIncludes.php`.

**Comment by paulohenriquesi** [comment]
Por nada!

Configurei para atualização automática no packagist! Obrigado pela dica!
