### ISSUE TITLE
Class 'Httpful\Bootstrap' not found

### ISSUE THREAD

**Issue by thiagolp90** [Braspag/BraspagApiPhpSdk#4]
Estou desenvolvendo um plugin para WooCommerce, mas quando dou o include do arquivo BraspagApiIncludes.php dentro do plugin da esse erro:

> Warning: include(phar://httpful.phar/Httpful/Bootstrap.php) [function.include]: failed to open stream: No such file or directory in /woocommerce-braspag/includes/BraspagApiPhpSdk/libs/httpful.phar on line 4

> Warning: include() [function.include]: Failed opening 'phar://httpful.phar/Httpful/Bootstrap.php' for inclusion (include_path='.') in /woocommerce-braspag/includes/BraspagApiPhpSdk/libs/httpful.phar on line 4

> Fatal error: Class 'Httpful\Bootstrap' not found in /woocommerce-braspag/includes/BraspagApiPhpSdk/libs/httpful.phar on line 5

Pesquisei sobre isso e eles falavam que usando o composer resolveria, mas o servidor do cliente não dá suporte. Alguma ideia?

**Comment by ArturSoares** [comment]
Boa tarde, Thiago. Você sabe informar qual é o servidor do cliente?

**Comment by thiagolp90** [comment]
A hospedagem (Terra Empresas) não dá suporte a nenhuma modificação no ambiente, e nem mesmo para eles fazerem. Estamos contratando outro serviço de hospedagem, atualizando, posto aqui.
