### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by hackin88** [Braspag/BraspagApiPhpSdk#5]
Ola

Boa Noite

1)

Seria muito bom colocar no packagist.org, só precisa criar o composer.json e criar a conta lá, bem tranquilo.

2)

Uma adaptação pra instalar com composer enquanto não tem suporte é colocar isso no composer.json (root):

	{
		"repositories": {
			"braspag/braspagapiphpsdk": {
				"type": "package",
				"package": {
				    "name": "braspag/braspagapiphpsdk",
				    "version": "master",
				    "source": {
				        "url": "https://github.com/Braspag/BraspagApiPhpSdk.git",
				        "type": "git",
				        "reference": "master",
				        "autoload": {
							"classmap": [
								"Models/",
								"libs/",
								"ApiServices.php",
								"BraspagApiConfig.php.example",
								"BraspagApiIncludes.php",
								"HttpStatus.php"
							]
				        }
				    }
				}
			}
		},
		"require": {
		    "hackin88/sinapses-api-php": "dev-master",
		    "braspag/braspagapiphpsdk": "dev-master"
		}
	}

**Comment by paulohenriquesi** [comment]
Fala aí, Hackin88!

Obrigado pela sugestão! Coloquei lá no composer!

https://packagist.org/packages/braspag/braspagapiphpsdk
